version: '2'
services:
    telcoprobackend-app:
        image: telcoprobackend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://telcoprobackend-mysql:3306/telcoprobackend?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    telcoprobackend-mysql:
        extends:
            file: mysql.yml
            service: telcoprobackend-mysql
